### ISSUE TITLE
Valid characters for JSON and XML differs: What could be done

### ISSUE THREAD

**Issue by kra3** [kordamp/json-lib#34]
Syntax rules for JSON and XMLs are not always compatible.
For example, A JSON data such as `{"16x16": "image_url"}` can't be converted to `<o><16x16>image_url</16x16></o>` as XML tag name can't be started with a number.

Is there a workaround for this already in place in the library, if yes what is it? if not what's the expected solution to address such scenarios?

**Comment by aalmiray** [comment]
The following snippet shows the new `mappedPropertyNames` option available in `XMLSerializer`:

```java
        JSONObject jsonObject = JSONObject.fromObject("{\"16x16\": \"image_url\"}");
        String expected = "<o><image_16x16 type=\"string\">image_url</image_16x16></o>";
        xmlSerializer.addMappedPropertyName("16x16", "image_16x16");
        String xml = xmlSerializer.write(jsonObject);
        assertXMLEqual(expected, xml);
```
