### ISSUE TITLE
Transition import from insecure commons-collections to collections4

### ISSUE THREAD

**Issue by thomaszbz** [kordamp/json-lib#62]
Version: 3.0.1 and latest 3.0.2 snapshot:

Dependency commons-collections:commons-collections is insecure via https://advisory.checkmarx.net/advisory/vulnerability/Cx78f40514-81ff/

According to documentation https://kordamp.org/json-lib/#_maven json-lib requires: Apache commons-collections4 4.4

So that formally, json-lib does not depend on the insecure package.

However, https://github.com/kordamp/json-lib/blob/master/subprojects/json-lib-core/src/main/java/org/kordamp/json/JsonConfig.java#L20 still points to `import org.apache.commons.collections.map.MultiKeyMap;`
which instead should be `import org.apache.commons.collections4.map.MultiKeyMap;` 

Currently, I get errors like 
`NoClassDefFoundError: Could not initialize class org.kordamp.json.JsonConfig` 
because of that.

**Comment by aalmiray** [comment]
Fixed in `3.0.2`.

**Comment by thomaszbz** [comment]
That went quick, and it did the trick. Thanks!
